# Site
repository: dhuzard/dhuzard.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Damien Huzard
title: Neuro-behaviorist, PhD
# email: damien.huzard@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# Social links
twitter_username: DHuzard
github_username:  dhuzard
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: dhuzard
# pinterest_username:
# youtube_username:
# googleplus_username:
orcid_username: 0000-0003-4820-7951

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/face-2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm D. Huzard, behavioral neuroscientist. > I like doing and trying stuff.
  My main research interests are gravitating around the concept of Adaptation, Stress, 
  social interactions, coping strategies which are linked to main physiological features, 
  such as cardiac regulation and sensory-processing.
  > I am an expert in <mark>all</mark> types of behavioral tasks with rodents. <br>
  > I know <mark>Python</mark> analysis tools: <mark>Numpy</mark>, <mark>Scipy</mark>, <mark>matplotlib</mark> and <mark>Git</mark>

content:
  - title: Lab Experience # Title for the section
    layout: list # Type of content section (list/text)
    
    content:
      - layout: left
        title: Bourinet lab, Inserm, IGF, Montpellier
        link: https://www.igf.cnrs.fr/index.php/en/h-teams-en/ht-bourinet-en
        link_text: lab website
        sub_title: "Postdoc #2"
        caption: July 2021 - present
        # quote: Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Studying the affects of Affective Touch on mice, along with Amaury François:
            - Analyzing Shank3 mouse model of ASD
            - Links with Heart rate variability features ?
            Technics used: Skin-Nerve recordings, Live Mouse Tracker (https://livemousetracker.org/), ... , .

      - layout: top-middle
        title: Paternity Leave
        sub_title: 4 months
        quote: Baby approved

      - layout: right
        title: Jeanneteau lab, Inserm, IGF, Montpellier
        # link: https://www.mdc-berlin.de/poulet
        # link_text: boringcompany.com
        sub_title: Postdoc
        caption: Feb 2019 - Feb 2021
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Studying social behaviors of mice model of Autism (Magel2-KO and Cntnap2-KO).
            I developped the Social Fear Conditioning protocol and the Live Mouse Tracker system in the laboratory.

      - layout: left
        title: Sandi lab, EPFL, Switzerland
        link: https://www.epfl.ch/labs/lgc/
        link_text: LGC lab
        sub_title: PhD candidate
        caption: March 2014 - June 2018
          #quote: >
          #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
                My PhD thesis ...
                
      - layout: right
        title: Mumby lab, Concordia University, Montreal.
        link: https://www.sissa.it/
        link_text: CSBN website
        sub_title: Master student
        caption: July 2012 - October 2013
          #quote: >
          #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
                Super cool stuff
         
  - title: Academic Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: EPFL, Lausanne, Switzerland
        caption: September 2011 - September 2013
        sub_title: Master's degree in Neuroscience
        # quote: 110/110 cum laude
        # description: | # this will include new lines to allow paragraphs
        # During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

      - layout: top-middle
        title: EPFL, Lausanne, Switzerland
        caption: September 2008 - September 2011
        sub_title: Bachelor's degree in Life Sciences
        # quote: 103/110 
        # description: | # this will include new lines to allow paragraphs


  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
       - **Somatostatin interneurons activated by 5-HT<sub>2A</sub> receptor suppress slow oscillations in medial entorhinal cortex.**\
        Elife. 2021 Mar 31;10:e66960. doi: 10.7554/eLife.66960. PMID: 33789079; PMCID: PMC8016478.\
        de Filippo R<sup>*</sup>, Rost BR, Stumpf A, Cooper C, Tukker JJ, Harms C, Beed P, Schmitz D<sup>*</sup>.\
        <sup>*</sup> = corresponding authors

        - **Layer 3 Pyramidal Cells in the Medial Entorhinal Cortex Orchestrate Up-Down States and Entrain the Deep Layers Differentially.** \
        Cell Rep. 2020 Dec 8;33(10):108470. doi: 10.1016/j.celrep.2020.108470. PMID: 33296656.\
        Beed P<sup>*</sup>, de Filippo R<sup>*</sup>, Holman C<sup>*</sup>, Johenning FW, Leibold C, Caputi A, Monyer H, Schmitz D.\
        <sup>*</sup> = equal contribution

        - **Pin1 Modulates the Synaptic Content of NMDA Receptors via Prolyl-Isomerization of PSD-95.** \
        J Neurosci. 2016 May 18;36(20):5437-47. doi: 10.1523/JNEUROSCI.3124-15.2016. PMID: 27194325; PMCID: PMC6601765.\
        Antonelli R, De Filippo R, Middei S, Stancheva S, Pastore B, Ammassari-Teule M, Barberis A, Cherubini E, Zacchi P. 

  - title: Conferences / Scientific meetings
    layout: text
    content: | # this will include new lines to allow paragraphs
        - **2022** FENS, Paris. Poster ‘’
        - **2020** FENS, Virtual. Poster ‘’
        - **2018** FENS, Berlin. Poster ‘’
        - **2018** MATRICS (EU FP7) General Assembly. Oral Presentation. Roma.
        - **2017** MATRICS (EU FP7) General Assembly. Oral Presentation. Majorca.
        - **2016** FENS, Copenhagen. Poster ‘’
        - **2016** MATRICS (EU FP7) General Assembly. Dublin.
        - **2015** Ettore Majorama Conference, Stress, the brain and the heart, Erice, Italy
        - **2014** FENS, Milan. Poster ‘’
        
  - title: Grants / Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
        - **2021** 1-year postdoc Founding, by the Lefoulon-Delalande foundation
        - **2020** FENS attendance voucher
        - **2018** FENS/IBRO Travel Grant

  - title: Various interests
    layout: text
    content: | # this will include new lines to allow paragraphs
        <p style="text-align:center">
          <img src="/images/IMG1.jpeg " width="300" title="title1"/>
          <img src="/images/IMG2.jpg" width="400" title="title1"/> 
          <img src="/images/IMG3.jpeg " width="400" title="title1"/>
        </p>
        <p style="text-align:center">
          <img src="/images/IMG1.jpeg " width="300" title="title1"/>
          <img src="/images/IMG2.jpg" width="400" title="title1"/> 
          <img src="/images/IMG3.jpeg " width="400" title="title1"/>
        </p>
        <p style="text-align:center">
          <img src="/images/IMG1.jpeg " width="300" title="title1"/>
          <img src="/images/IMG2.jpg" width="400" title="title1"/> 
          <img src="/images/IMG3.jpeg " width="400" title="title1"/>
        </p>
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
