# Site
repository: dhuzard/dhuzard.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Damien Huzard
title: Neuro-behaviorist, PhD
# email: damien.huzard@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# Social links
twitter_username: DHuzard
github_username:  dhuzard
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: dhuzard
# pinterest_username:
# youtube_username:
# googleplus_username:
orcid_username: 0000-0003-4820-7951

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/face-2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Damien, behavioral neuroscientist or <b>neuro-behaviorist</b>, sounds fancier.... > I like doing and trying stuff.
  My main research interests are gravitating around the concept of Adaptation, Stress, 
  social interactions, coping strategies which are linked to main physiological features, 
  such as cardiac regulation and sensory-processing.
  > I am an expert in <mark>behavioral experiments</mark> with rodents. <br>
  > I know <mark>Python</mark> analysis tools: <mark>Numpy</mark>, <mark>Scipy</mark>, <mark>matplotlib</mark> and <mark>Git</mark>
  > I combine behavioral tests with <mark>physiological</mark> parameters, such as: <mark>ECG/HRV</mark> and <mark>Skin-Nerve</mark> recordings.

content:
  - title: Lab Experience # Title for the section
    layout: list # Type of content section (list/text)
    
    content:
      - layout: left
        title: Bourinet lab, <br> Inserm, IGF, <br> Montpellier, France
        link: https://www.igf.cnrs.fr/index.php/en/h-teams-en/ht-bourinet-en
        link_text: lab website
        sub_title: "Postdoc #2"
        caption: July 2021 - present
        # quote: Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Studying the affects of Affective Touch on mice, along with Amaury François:
            - Analyzing Shank3 mouse model of ASD
            - Links with Heart rate variability features ?
            Technics used: Skin-Nerve recordings, Live Mouse Tracker (https://livemousetracker.org/), ... , .

      - layout: top-middle
        title: Paternity Leave
        sub_title: 4 months
        quote: Baby approved

      - layout: right
        title: Jeanneteau lab, <br> Inserm, IGF, <br> Montpellier, France
        sub_title: "Postdoc #1"
        caption: Feb 2019 - Feb 2021
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Studying social behaviors of mice model of Autism (Magel2-KO and Cntnap2-KO).
            I developped the Social Fear Conditioning protocol and the Live Mouse Tracker system in the laboratory.

      - layout: left
        title: Sandi lab, EPFL, Switzerland
        link: https://www.epfl.ch/labs/lgc/
        link_text: LGC lab
        sub_title: PhD candidate
        caption: March 2014 - June 2018
          #quote: >
          #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
                My PhD thesis ...
                
      - layout: right
        title: Mumby lab, <br> Concordia University, <br> Montreal.
        link: https://www.concordia.ca/research/neuroscience.html
        link_text: CSBN website
        sub_title: Master student
        caption: July 2012 - October 2013
        quote: The effects of extrinsic stress on somatic markers and behavior are dependent on animal housing conditions, D. Huzard et al., Physiology and Behavior, 2015
        description: | # this will include new lines to allow paragraphs
                Studying the benefical effects of Enriched Environments on stressed rats.
         
  - title: Academic Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: EPFL, Lausanne, Switzerland
        caption: September 2011 - September 2013
        sub_title: Master's degree in Neuroscience
        # quote: 110/110 cum laude
        # description: | # this will include new lines to allow paragraphs
        # During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

      - layout: top-middle
        title: EPFL, Lausanne, Switzerland
        caption: September 2008 - September 2011
        sub_title: Bachelor's degree in Life Sciences
        # quote: 103/110 
        # description: | # this will include new lines to allow paragraphs


  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
       - **The impact of C-tactile low-threshold mechanoreceptors on affective touch and social interactions in mice.**\
        Science advances. 2022 June 29; Vol 8, Num 26 eabo7566. doi: 10.1126/sciadv.abo7566. PMID:  35767616; PMCID: PMC9242590.\
        <b>Damien Huzard</b>, Miquel Martin, François Maingret, Jean Chemin, Freddy Jeanneteau, Pierre-François Mery, Pascal Fossat, Emmanuel Bourinet, and Amaury François.\

        - **Constitutive differences in glucocorticoid responsiveness are related to divergent spatial information processing abilities.** \
        Stress. 2020 Jan;23(1):37-49. doi: 10.1080/10253890.2019.1625885. Epub 2019 Jun 12. PMID: 31187686.\
        <b>Huzard D</b>, Vouros A, Monari S, Astori S, Vasilaki E, Sandi C.\

        - **Low vagal tone in two rat models of psychopathology involving high or low corticosterone stress responses.** \
        Psychoneuroendocrinology. 2019 Mar;101:101-110. doi: 10.1016/j.psyneuen.2018.11.003. Epub 2018 Nov 3. PMID: 30448728.\
        <b>Huzard D</b>, Ghosal S, Grosse J, Carnevali L, Sgoifo A, Sandi C. \
        
        - **Low empathy-like behaviour in male mice associates with impaired sociability, emotional memory, physiological stress reactivity and variations in neurobiological regulations.**\
        PLoS One. 2017 Dec 4;12(12):e0188907. doi: 10.1371/journal.pone.0188907. PMID: 29200428; PMCID: PMC5714342.\
        Laviola G, Zoratto F, Ingiosi D, Carito V, <b>Huzard D</b>, Fiore M, Macrì S.\

        - **The link between aberrant hypothalamic-pituitary-adrenal axis activity during development and the emergence of aggression-Animal studies.** \
        Neurosci Biobehav Rev. 2018 Aug;91:138-152. doi: 10.1016/j.neubiorev.2016.10.008. Epub 2016 Oct 14. PMID: 27751733.\
        Walker SE<sup>*</sup>, Papilloud A<sup>*</sup>, Huzard D<sup>*</sup>, Sandi C.\
        <sup>*</sup>equal contribution.\
        
        - **Urolithin A induces mitophagy and prolongs lifespan in C. elegans and increases muscle function in rodents.** \
        Nat Med. 2016 Aug;22(8):879-88. doi: 10.1038/nm.4132. Epub 2016 Jul 11. PMID: 27400265.\
        Ryu D, Mouchiroud L, Andreux PA, Katsyuba E, Moullan N, Nicolet-Dit-Félix AA, Williams EG, Jha P, Lo Sasso G, <b>Huzard D</b>, Aebischer P, Sandi C, Rinsch C, Auwerx J.\

        - **The effects of extrinsic stress on somatic markers and behavior are dependent on animal housing conditions.** \
        Physiol Behav. 2015 Nov 1;151:238-45. doi: 10.1016/j.physbeh.2015.07.018. Epub 2015 Jul 26. PMID: 26220463.\
        <b>Huzard D</b>, Mumby DG, Sandi C, Poirier GL, van der Kooij MA. \

  - title: Conferences / Scientific meetings
    layout: text
    content: | # this will include new lines to allow paragraphs
        - **2022** Spin-Days, Sète. Oral Presentation, <b>The skin is the new brain</b> ‘’
        - **2022** FENS, Paris. Poster ‘’
        - **2020** FENS, Virtual. Poster ‘’
        - **2019** Invited Talk by Vincent Prevost, Inserm Lille
        - **2018** FENS, Berlin. Poster ‘’
        - **2018** MATRICS (EU FP7) General Assembly. Oral Presentation. Roma.
        - **2017** MATRICS (EU FP7) General Assembly. Oral Presentation. Majorca.
        - **2016** FENS, Copenhagen. Poster ‘’
        - **2016** MATRICS (EU FP7) General Assembly. Dublin.
        - **2015** Ettore Majorama Conference, <b>Stress, the brain and the heart</b>, Erice, Italy
        - **2014** FENS, Milan. Poster ‘’
        
  - title: Grants / Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
        - **2021** 1-year postdoc Founding, by the Lefoulon-Delalande foundation
        - **2020** FENS attendance voucher
        - **2018** FENS/IBRO Travel Grant

  - title: Press / Populare science
    layout: text
    content: | # this will include new lines to allow paragraphs
        - **Neurosapiens Podcast** Nov 2022, on Social contacts <a href="https://podcast.ausha.co/neurosapiens/47-celui-ou-on-parlait-de-la-puissance-du-contact-humain">audio link</a>
        - **Cerveaux et Psycho** Oct 2022, Le toucher fondement du lien social, <a href="https://www.cerveauetpsycho.fr/sd/neurosciences/le-toucher-fondement-du-lien-social-24335.php">online article link</a>
        - **Espiloon** 2021, Le pouvoir des Caresses, on issue N°147

  - title: Various Stuffs that keep my mind busy
    layout: text
    content: | # this will include new lines to allow paragraphs
        <p style="text-align:center">
          <img src="/images/blackhole.jpg " width="350" title="General Science Stuff"/>
          <img src="/images/blob.jpg" width="350" title="Fun Science Stuff"/> 
        </p>
        <p style="text-align:center">
          <img src="/images/nervous.png " width="300" title="Some Art Stuff"/>
          <img src="/images/PA300431.JPG " width="300" title="title1"/> 
          <img src="/images/2 mice doing drugs - painting by Dali.png " width="300" title="title1"/>
        </p>
        <p style="text-align:center">
          <img src="/images/Damien-LMT-1.jpg " width="500" title="title1"/>
          <img src="/images/1h5mj1fg1kc7a0000000000 (2).jpg " width="500" title="blaxtractattoos.com"/>
        </p>
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
